name: CICD Factorial

on:
  push:
    branches: [main]

jobs:
  testing_first:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest